package com.example.dish_memo.friend.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;

/**
 * Request body containing the signed friend invitation token.
 *
 * @param inviteToken token generated by the inviter
 */
public record FriendInviteTokenRequest(@NotBlank(message = "inviteToken is required") @JsonProperty("inviteToken") String inviteToken) {
}
